spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ecotech-api

  datasource:
    url: jdbc:postgresql://localhost:5433/ecotech
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 3600
    issuer: ecotech-api

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}

  ses:
    from-email: ${AWS_SES_FROM_EMAIL}
    region: ${AWS_REGION}

app:
  base-url: ${APP_BASE_URL}

logging:
  level:
    org.hibernate.SQL: debug
